spring.application.name=scm2

server.port=8083

#data source url
# PostgreSQL DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/scm2
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Optional: Logging SQL statements
logging.level.org.hibernate.SQL=DEBUG
